frameworkVersion: '3'
service: uzawa-transfer-message-to-channel
provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
          Resource: "*"
  httpApi:
    disableDefaultEndpoint: true
  environment:
    SERVERLESS_STAGE: ${opt:stage, 'prod'}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    WORKSPACE_NAME: ${env:WORKSPACE_NAME}
    DESTINATION_CHANNEL_ID: ${env:DESTINATION_CHANNEL_ID}

functions:
  app:
    handler: app.handler
    events:
      - httpApi:
          path: /slack/events
          method: post

package:
  patterns:
    - "!.venv/**"
    - "!.vscode/**"
    - "!node_modules/**"
    - "!.env"

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
custom:
  pythonRequirements:
    pythonBin: .venv/bin/python
    zip: true
    slim: true
  customDomain:	
    domainName: nodoka.slackbot.utgw.net
    certificateName: '*.slackbot.utgw.net'
    basePath: ''
    createRoute53Record: true
    endpointType: regional
    apiType: http
