frameworkVersion: "3"
configValidationMode: error
service: uzawa-transfer-message-to-channel
provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
          Resource: arn:aws:lambda:ap-northeast-1:747582436141:function:uzawa-transfer-message-to-channel-dev-app
  httpApi:
    disableDefaultEndpoint: true
  environment:
    SERVERLESS_STAGE: ${opt:stage, 'prod'}
    SLACK_SIGNING_SECRET: ${ssm:/uzawa/slack-signing-secret}
    SLACK_BOT_TOKEN: ${ssm:/uzawa/slack-bot-token}
    WORKSPACE_NAME: kmc-jp
    DESTINATION_CHANNEL_ID: C03QHCTLW76

functions:
  app:
    handler: app.handler
    events:
      - httpApi:
          path: /slack/events
          method: post

package:
  patterns:
    - "!.venv/**"
    - "!.vscode/**"
    - "!node_modules/**"
    - "!.env"

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
custom:
  pythonRequirements:
    pythonBin: .venv/bin/python
    zip: true
    slim: true
  customDomain:
    domainName: nodoka.slackbot.utgw.net
    certificateName: "*.slackbot.utgw.net"
    basePath: ""
    createRoute53Record: true
    endpointType: regional
    apiType: http
